version: '3.1'

services:
  webapp-node:
    build: .
    ports:
      - 3000:3000
    networks:
      - webapp-network

  webapp-mongo:
    image: mongo
    networks:
      - webapp-network

networks:
  webapp-network:
